### ISSUE TITLE
Chapter 8, Page 200 typo: Wrong section number referenced for ISP

### ISSUE THREAD

**Issue by UnHumbleBen** [prmr/DesignBook#10]
Current version:
> Fortunately, we saw how to deal with this situation with the Interface Segregation Principle (ISP, see Section __3.2__).

Correction:
> Fortunately, we saw how to deal with this situation with the Interface Segregation Principle (ISP, see Section __3.8__).

**Comment by prmr** [comment]
Thanks, I've added this to the errata (and you to the [acknowledgements](https://github.com/prmr/DesignBook#acknowledgements)).
