### ISSUE TITLE
Chapter 8, Page 234 - Missing line break in code sample

### ISSUE THREAD

**Issue by cjoudrey** [prmr/DesignBook#11]
Hello @prmr,

I wanted to let you know that there is missing a line break on line 7 of the code sample on page 234.

The code is still readable, but could be a quick fix in the next version. 😄 

<img width="1863" alt="Screenshot 2022-12-07 at 11 40 10 PM" src="https://user-images.githubusercontent.com/385270/206358064-feddc251-d549-48c4-9654-406382c9e2a9.png">

**Comment by prmr** [comment]
Thanks. Actually I had to squeeze this one in to fit the text in the page.
