### ISSUE TITLE
Chapter 4, page 77 small typo

### ISSUE THREAD

**Issue by joshuamanascu** [prmr/DesignBook#15]
Hi prof @prmr ,

Just wanted to let you know on page 77, at the end of the *Special values of an enumerated type* bullet point, that:
> although we have four ranks and 13 suits

Should probably be reversed, like so:

> although we have 13 ranks and four suits

Cheers!

**Comment by prmr** [comment]
Ooops, thanks for flagging, I've added it to the errata.
