### ISSUE TITLE
Deprecated libraries in Chapter 8

### ISSUE THREAD

**Issue by Vermillion-Chen** [prmr/DesignBook#17]
The following Java libraries are deprecated because of a [lack of event richness](https://bugs.openjdk.org/browse/JDK-8154801): 
- `java.util.Observable`
- `java.util.Observer`

Other libraries such as `java.beans.PropertyChangeListener`, `java.beans.PropertyChangeSupport`, `java.util.concurrent.Flow` are more versatile (and might be worth expanding on in class!).

**Comment by prmr** [comment]
Note that the references to `Observer` and `Observable` in Chapter 8 are to user-defined types of these names, not the JDK versions. I'll clarify with a footnote in the next edition.
