### ISSUE TITLE
Typo 9.4, Page 255 `comparator` should be `Comparator`

### ISSUE THREAD

**Issue by UnHumbleBen** [prmr/DesignBook#7]
Currently, the book calls `comparator.comparing`, but `comparator` is the name of an instance that has not been constructed yet.
```java
Comparator<Card> comparator =
comparator.comparing(Card::getSuit());
```
The correct code should be capitalized `Comparator.comparing` because `comparing` is a static method in the `Comparator` class.
```java
Comparator<Card> comparator =
Comparator.comparing(Card::getSuit());
```

**Comment by prmr** [comment]
Thanks, I added this to the errata.
